In [1]:
import requests
import pandas as pd
import numpy as np
from datetime import date
import import_ipynb
import covid_dict as cd

importing Jupyter notebook from covid_dict.ipynb

1) [Remover colunas dos atributos desconsiderados](#remove_column)  
2) [Arrumando os dados](#data_fix)  
3) [Gerando a matrix binária](#binary_matrix)  
3.1) [Matriz: Óbitos](#binary_matrix_obito)   
3.2) [Matriz: Recuperados](#binary_matrix_rec)  
3.3) [Matriz: Assintomáticos](#binary_matrix_assin)  
3.4) [Matriz: Sintomáticos](#binary_matrix_sin)  

[Panda](Panda_dataset.ipynb)

[Dicionário de dados](covid_dict.ipynb)

In [2]:
# csv_url = "https://ti.saude.rs.gov.br/covid19/download"
#today = date.today()
# dataset = f'dataset-{today}.csv'

# req = requests.get(csv_url)
# url_content = req.content
# csv_file = open(dataset, 'wb')

# csv_file.write(url_content)
# csv_file.close()

In [3]:
df = pd.read_csv('20201030.csv', sep=',')  #nrows=1000

Atributos desconsiderados:
* COD_IBGE
* MUNICIPIO
* COD_REGIAO_COVID
* DATA_SINTOMAS
* DATA_EVOLUCAO
* DATA_INCLUSAO_OBITO
* DATA_EVOLUCAO_ESTIMADA
* ETNIA_INDIGENA
* FONTE_INFORMACAO
* PAIS_NASCIMENTO
* BAIRRO

#### 1) Remover colunas dos atributos desconsiderados <a name="remove_column"></a>

In [4]:
for e in cd.attr_removed3:
    del df[e]

#### 2) Filtrando registros -- EVOLUCAO == OBITO

In [5]:
df.head()

,REGIAO_COVID,SEXO,FAIXAETARIA,CRITERIO,DATA_CONFIRMACAO,EVOLUCAO,HOSPITALIZADO,FEBRE,TOSSE,GARGANTA,DISPNEIA,OUTROS,CONDICOES,GESTANTE,DATA_INCLUSAO_OBITO,RACA_COR,PROFISSIONAL_SAUDE,HOSPITALIZACAO_SRAG,PES_PRIV_LIBERDADE
0,PASSO FUNDO - R17 R18 R19,Feminino,50 a 59,RT-PCR,23/08/2020,OBITO,SIM,SIM,SIM,SIM,SIM,NAO,"Doença Cardiovascular Crônica, Obesidade, Outros",NAO,02/09/2020,BRANCA,NAO INFORMADO,SIM,NAO
1,PASSO FUNDO - R17 R18 R19,Masculino,70 a 79,RT-PCR,27/08/2020,OBITO,SIM,SIM,SIM,NAO,SIM,NAO,Doença Cardiovascular Crônica,NAO,19/10/2020,BRANCA,NAO INFORMADO,SIM,NAO
2,SANTA MARIA - R01 R02,Masculino,70 a 79,RT-PCR,11/07/2020,OBITO,SIM,NAO,NAO,NAO,SIM,NAO,"Doença Cardiovascular Crônica, Diabetes mellitus",NAO,23/09/2020,BRANCA,NAO INFORMADO,SIM,NAO
3,IJUI - R13,Feminino,80 e mais,RT-PCR,16/09/2020,OBITO,SIM,NAO,SIM,NAO,SIM,NAO,"Outra Pneumatopatia Crônica, Outros",NAO,29/09/2020,BRANCA,NAO INFORMADO,SIM,NAO
4,SANTA ROSA - R14,Masculino,50 a 59,RT-PCR,28/05/2020,OBITO,SIM,NAO,SIM,NAO,SIM,NAO,"Doença Cardiovascular Crônica, Síndrome de Down",NAO,19/10/2020,BRANCA,NAO INFORMADO,SIM,NAO

In [6]:
df = df[df.eq('OBITO').any(axis=1)]

#### 3) Arrumando os dados - FAIXAETARIA, DATA_CONFIRMACAO, CONDICOES <a name="data_fix"></a>

Faixa Etária
* < 1: Bebê
* (01,09): Criança
* (10, 19): Jovem
* (20, 39): Adulto 1
* (40, 49): Adulto 2
* (50, 59): Adulto 3
* (60, 69): Idoso 1
* (70, 79): Idoso 2
* (80 +): Idoso 3

In [7]:
for index, row in df.iterrows():
    if row['FAIXAETARIA'] == '<1':
        row['FAIXAETARIA'] = 'Bebê'
    elif row['FAIXAETARIA'] == '01 a 04' or row['FAIXAETARIA'] == '05 a 09':
        row['FAIXAETARIA'] = 'Criança'
    elif row['FAIXAETARIA'] == '10 a 14' or row['FAIXAETARIA'] == '15 a 19':
        row['FAIXAETARIA'] = 'Jovem'
    elif row['FAIXAETARIA'] == '20 a 29' or row['FAIXAETARIA'] == '30 a 39':
        row['FAIXAETARIA'] = 'Adulto_1'
    elif row['FAIXAETARIA'] == '40 a 49':
        row['FAIXAETRIA'] = 'Adulto_2'
    elif row['FAIXAETARIA'] == '50 a 59':
        row['FAIXAETARIA'] = 'Adulto_3'
    elif row['FAIXAETARIA'] == '60 a 69':
        row['FAIXAETARIA'] = 'Idoso_1'
    elif row['FAIXAETARIA'] == '70 a 79':
        row['FAIXAETARIA'] = 'Idoso_2'
    else:
        row['FAIXAETARIA'] = 'Idoso_3'

Intervalo entre confirmação da Covid e confirmação do Óbito

In [8]:
dt_conf = pd.to_datetime(df['DATA_CONFIRMACAO'],dayfirst=True)
dt_obito = pd.to_datetime(df['DATA_INCLUSAO_OBITO'],dayfirst=True)
df['INTERNACAO'] = round(((dt_obito - dt_conf).dt.days),-1)

Data de Confirmação Covid-19

In [9]:
for index, row in df.iterrows():
    mes = row['DATA_CONFIRMACAO'].split('/')
    if mes[1] == '02':
        row['DATA_CONFIRMACAO'] = 'Fevereiro'
    elif mes[1] == '03':
        row['DATA_CONFIRMACAO'] = 'Março'
    elif mes[1] == '04':
        row['DATA_CONFIRMACAO'] = 'Abril'
    elif mes[1] == '05':
        row['DATA_CONFIRMACAO'] = 'Maio'    
    elif mes[1] == '06':
        row['DATA_CONFIRMACAO'] = 'Junho'
    elif mes[1] == '07':
        row['DATA_CONFIRMACAO'] = 'Julho'
    elif mes[1] == '08':
        row['DATA_CONFIRMACAO'] = 'Agosto'
    elif mes[1] == '09':
        row['DATA_CONFIRMACAO'] = 'Setembro'
    else:
        row['DATA_CONFIRMACAO'] = 'Outubro'

Data de confirmação óbito

In [10]:
for index, row in df.iterrows():
    mes = row['DATA_INCLUSAO_OBITO'].split('/')
    if mes[1] == '02':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Fevereiro'
    elif mes[1] == '03':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Março'
    elif mes[1] == '04':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Abril'
    elif mes[1] == '05':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Maio'    
    elif mes[1] == '06':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Junho'
    elif mes[1] == '07':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Julho'
    elif mes[1] == '08':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Agosto'
    elif mes[1] == '09':
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Setembro'
    else:
        row['DATA_INCLUSAO_OBITO'] = 'Obito_Outubro'

Condições (Comorbidades)

In [11]:
for e in cd.comorbidades:
    df[e] = str(np.nan)
    
for index, row in df.iterrows():
    if 'asma' in str(row['CONDICOES']).lower():
        row['asma'] = 'SIM'
    else:
        row['asma'] = 'NAO'
    if 'respirató' in str(row['CONDICOES']).lower():
        row['d_respiratoria'] = 'SIM'
    else:
        row['d_respiratoria'] = 'NAO'
    if 'outro' in str(row['CONDICOES']).lower():
        row['outras_comorbidades'] = 'SIM'
    else:
        row['outras_comorbidades'] = 'NAO'
    if 'outro' in str(row['CONDICOES']).lower():
        row['outras_comorbidades'] = 'SIM'
    else:
        row['outras_comorbidades'] = 'NAO'
    if 'cromossômicas' in str(row['CONDICOES']).lower():
        row['d_cromossomica'] = 'SIM'
    else:
        row['d_cromossomica'] = 'NAO'
    if 'neuro' in str(row['CONDICOES']).lower():
        row['d_neurologica'] = 'SIM'
    else:
        row['d_neurologica'] = 'NAO'
    if 'diabe' in str(row['CONDICOES']).lower():
        row['diabetes'] = 'SIM'
    else:
        row['diabetes'] = 'NAO'
    if 'imuno' in str(row['CONDICOES']).lower():
        row['imunodeficiencia'] = 'SIM'
    else:
        row['imunodeficiencia'] = 'NAO'
    if 'rena' in str(row['CONDICOES']).lower():
        row['d_renal'] = 'SIM'
    else:
        row['d_renal'] = 'NAO'
    if 'hepát' in str(row['CONDICOES']).lower():
        row['d_hepatica'] = 'SIM'
    else:
        row['d_hepatica'] = 'NAO'
    if 'hemato' in str(row['CONDICOES']).lower():
        row['d_hematologica'] = 'SIM'
    else:
        row['d_hematologica'] = 'NAO'
    if 'card' in str(row['CONDICOES']).lower():
        row['d_cardiaca'] = 'SIM'
    else:
        row['d_cardiaca'] = 'NAO'
    if 'obes' in str(row['CONDICOES']).lower():
        row['obesidade'] = 'SIM'
    else:
        row['obesidade'] = 'NAO'
    if 'down' in str(row['CONDICOES']).lower():
        row['sindrome_down'] = 'SIM'
    else:
        row['sindrome_down'] = 'NAO'
del df['CONDICOES']

### Gerando a matrix binária <a name="binary_matrix"></a>

In [12]:
# for e in cd.municipio:
#     df[e] = df.apply(lambda row: 1 if row.MUNICIPIO == e else 0, axis=1)

for e in cd.regiao_covid:
    df[e] = df.apply(lambda row: 'SIM' if row.REGIAO_COVID == e else 'NAO', axis=1)
    
for e in cd.faixa_etaria2:
    df[e] = df.apply(lambda row: 'SIM' if row.FAIXAETARIA == e else 'NAO', axis=1)
    
for e in cd.testagem: 
    df[e] = df.apply(lambda row: 'SIM' if row.CRITERIO == e else 'NAO', axis=1)

for e in cd.meses:
    df[e] = df.apply(lambda row: 'SIM' if row.DATA_CONFIRMACAO == e else 'NAO', axis=1)
    
for e in cd.meses_obito:
    df[e] = df.apply(lambda row: 'SIM' if row.DATA_INCLUSAO_OBITO == e else 'NAO', axis=1)
        
for e in cd.etnia:
    df[e] = df.apply(lambda row: 'SIM' if row.RACA_COR == e else 'NAO', axis=1)

In [13]:
df['SexF'] = df.apply(lambda row: 'SIM' if row.SEXO == 'Feminino' else 'NAO', axis=1)
df['SexM'] = df.apply(lambda row: 'SIM' if row.SEXO == 'Masculino' else 'NAO', axis=1)
df['Hospitalizado'] = df.apply(lambda row: 1 if row.HOSPITALIZADO == 'SIM' else 'NAO', axis=1)
df['Hosp_SRAG'] = df.apply(lambda row: 'SIM' if row.HOSPITALIZACAO_SRAG == 'SIM' else 'NAO', axis=1)
df['Prof_Saude'] = df.apply(lambda row: 'SIM' if row.PROFISSIONAL_SAUDE == 'SIM' else 'NAO', axis=1)
df['Febre'] = df.apply(lambda row: 'SIM' if row.FEBRE == 'SIM' else 'NAO', axis=1)
df['Tosse'] = df.apply(lambda row: 'SIM' if row.TOSSE == 'SIM' else 'NAO', axis=1)
df['Garganta'] = df.apply(lambda row: 'SIM' if row.GARGANTA == 'SIM' else 'NAO', axis=1)
df['Dispneia'] = df.apply(lambda row: 'SIM' if row.DISPNEIA == 'SIM' else 'NAO', axis=1)
df['Outros_Sint'] = df.apply(lambda row: 'SIM' if row.OUTROS == 'SIM' else 'NAO', axis=1)
df['Gestante'] = df.apply(lambda row: 'SIM' if row.GESTANTE == 'SIM' else 'NAO', axis=1)
df['Presidiario'] = df.apply(lambda row: 'SIM' if row.PES_PRIV_LIBERDADE == 'SIM' else 'NAO', axis=1)
df['Asma'] = df.apply(lambda row: 'SIM' if row.asma == 'SIM' else 'NAO', axis=1)
df['DRespiratoria'] = df.apply(lambda row: 'SIM' if row.d_respiratoria == 'SIM' else 'NAO', axis=1)
df['DNeurologica'] = df.apply(lambda row: 'SIM' if row.d_neurologica == 'SIM' else 'NAO', axis=1)
df['Diabetes'] = df.apply(lambda row: 'SIM' if row.diabetes == 'SIM' else 'NAO', axis=1)
df['Imunodef'] = df.apply(lambda row: 'SIM' if row.imunodeficiencia == 'SIM' else 'NAO', axis=1)
df['DRenal'] = df.apply(lambda row: 'SIM' if row.d_renal == 'SIM' else 'NAO', axis=1)
df['DHepatica'] = df.apply(lambda row: 'SIM' if row.d_hepatica == 'SIM' else 'NAO', axis=1)
df['DCardiaca'] = df.apply(lambda row: 'SIM' if row.d_cardiaca == 'SIM' else 'NAO', axis=1)
df['Obesidade'] = df.apply(lambda row: 'SIM' if row.obesidade == 'SIM' else 'NAO', axis=1)
df['Outras_Comorbidades'] = df.apply(lambda row: 'SIM' if row.outras_comorbidades == 'SIM' else 'NAO', axis=1)
df['DCromossomica'] = df.apply(lambda row: 'SIM' if row.d_cromossomica == 'SIM' else 'NAO', axis=1)
df['DHematologica'] = df.apply(lambda row: 'SIM' if row.d_hematologica == 'SIM' else 'NAO', axis=1)
df['Sindrome_down'] = df.apply(lambda row: 'SIM' if row.sindrome_down == 'SIM' else 'NAO', axis=1)

In [14]:
for e in cd.old_columns3:
    del df[e]

In [15]:
df

,INTERNACAO,BAGE - R22,PASSO FUNDO - R17 R18 R19,SANTA MARIA - R01 R02,IJUI - R13,SANTA ROSA - R14,URUGUAIANA - R03,PALMEIRA DAS MISSOES - R15 R20,CAXIAS DO SUL - R23 R24 R25 R26,PORTO ALEGRE - R10,...,Diabetes,Imunodef,DRenal,DHepatica,DCardiaca,Obesidade,Outras_Comorbidades,DCromossomica,DHematologica,Sindrome_down
0,10,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
1,50,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
2,70,NAO,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
3,10,NAO,NAO,NAO,SIM,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
4,140,NAO,NAO,NAO,NAO,SIM,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5729,10,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
5730,0,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
5731,10,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
5732,20,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
5733,20,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO

In [16]:
df.to_csv("20201030_binary_matrix(region)(yn).csv", header=None, index=False)

In [17]:
nome_atributos = df.columns.values.tolist()
df_dict = {i : nome_atributos[i] for i in range(0, len(nome_atributos))}

In [18]:
df.to_csv("20201030_binary_matrix(header)(yn).csv", index=False)

In [19]:
df.head()

,INTERNACAO,BAGE - R22,PASSO FUNDO - R17 R18 R19,SANTA MARIA - R01 R02,IJUI - R13,SANTA ROSA - R14,URUGUAIANA - R03,PALMEIRA DAS MISSOES - R15 R20,CAXIAS DO SUL - R23 R24 R25 R26,PORTO ALEGRE - R10,...,Diabetes,Imunodef,DRenal,DHepatica,DCardiaca,Obesidade,Outras_Comorbidades,DCromossomica,DHematologica,Sindrome_down
0,10,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
1,50,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
2,70,NAO,NAO,SIM,NAO,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
3,10,NAO,NAO,NAO,SIM,NAO,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO
4,140,NAO,NAO,NAO,NAO,SIM,NAO,NAO,NAO,NAO,...,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO,NAO